services:
  cups:
    build: .
    container_name: cups
    restart: unless-stopped
    network_mode: host # use host network to keep things simple
    devices:
      - /dev/bus/usb/009/003:/dev/bus/usb/009/003:rwm # hardcoded usb port
#    volumes:
#      - ./config:/etc/cups
    environment:
        - CUPSADMIN="${CUPS_ADMIN}"
        - CUPSPASSWORD="${CUPS_PASSWORD}"
        - TZ="${TZ}"
